version: '3.1'

services:
  database:
    image: "postgres:13-alpine"
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:

